[cond_simu, pc, marker_sizes, colors, disp_names] = store_cond_var_from_struct(dataStruct, 'cond__mdft');

fig = my_scatter('plot', 'Conductivity',...
    repmat(pc, numel(disp_names), 1), 'Closure stress [psi]', 'normal', ...
    cond_simu, 'Conductivity [md-ft]', 'log', ...
    marker_sizes, colors, disp_names);

fig2 = my_scatter('box', 'Conductivity',...
    repmat(pc, numel(disp_names), 1), 'Closure stress [psi]', 'normal', ...
    cond_simu, 'Conductivity [md-ft]', 'log', ...
    marker_sizes, colors, disp_names);